kind: pipeline
type: docker
name: default

steps:
  # Main branch
  - name: docker
    image: plugins/docker
    when:
      branch:
        - master
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: fascinated/checkip
      tags: latest
